"""Generate checked-in TypeScript from Pydantic's input/output JSON schemas."""

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pydantic import TypeAdapter

from database import schemas as s
from database.types import MessageRole, RunStatus, SessionStatus
from rpc_contract import RPC_METHODS

TARGET = Path(__file__).resolve().parents[2] / "frontend/src/generated/rpcContract.ts"


def typescript(schema: dict[str, Any], prefix: str = "") -> str:
    if "$ref" in schema:
        return prefix + schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript(item, prefix) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind in {"integer", "number"}:
        return "number"
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind == "array":
        return f"Array<{typescript(schema['items'], prefix)}>"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            fields = [
                f"{json.dumps(name)}{'' if name in required else '?'}: {typescript(value, prefix)}"
                for name, value in schema["properties"].items()
            ]
            return (
                "{ " + "; ".join(fields) + " }" if fields else "Record<string, never>"
            )
        additional = schema.get("additionalProperties", {})
        value = (
            typescript(additional, prefix)
            if isinstance(additional, dict)
            else "unknown"
        )
        return f"Record<string, {value}>"
    if not schema or set(schema) <= {"title", "default", "description"}:
        return "unknown"
    raise ValueError(f"Unsupported JSON schema: {schema}")


def generate() -> str:
    definitions: dict[str, str] = {}

    def convert(adapter: TypeAdapter, mode: str) -> str:
        schema = adapter.json_schema(mode=mode)
        prefix = "Input" if mode == "validation" else ""
        for name, definition in schema.get("$defs", {}).items():
            name = prefix + name
            rendered = typescript(definition, prefix)
            if name in definitions and definitions[name] != rendered:
                raise ValueError(f"Conflicting definition: {name}")
            definitions[name] = rendered
        rendered = typescript(schema, prefix)
        if schema.get("type") == "object" and "title" in schema:
            name = prefix + schema["title"]
            if name in definitions and definitions[name] != rendered:
                raise ValueError(f"Conflicting definition: {name}")
            definitions[name] = rendered
            return name
        return rendered

    methods = []
    for name, spec in sorted(RPC_METHODS.items()):
        params = convert(TypeAdapter(spec.params), "validation")
        result = convert(TypeAdapter(spec.result), "serialization")
        methods.append(
            f"  {json.dumps(name)}: {{ params: {params}; result: {result} }}"
        )
    aliases = {
        "Workspace": s.WorkspaceRecord,
        "Session": s.SessionRecord,
        "Run": s.RunRecord,
        "StoredMessage": s.MessageRecord,
        "StoredActivityEvent": s.RunEventRecord,
        "SessionHistory": s.SessionHistoryRecord,
        "SessionStatus": SessionStatus,
        "RunStatus": RunStatus,
        "MessageRole": MessageRole,
    }
    rendered_aliases = {
        name: convert(TypeAdapter(value), "serialization")
        for name, value in aliases.items()
    }
    return "\n".join(
        [
            "// Generated by backend/tools/generate_rpc_contract.py. Do not edit.",
            "// Inputs use validation schemas; results use serialization schemas.",
            *[
                f"export type {name} = {value}"
                for name, value in sorted(definitions.items())
            ],
            *[
                f"export type {name} = {value}"
                for name, value in rendered_aliases.items()
            ],
            "export type RpcMethodMap = {",
            *methods,
            "}",
            "export type RpcMethod = keyof RpcMethodMap",
            "export type RpcParams<M extends RpcMethod> = RpcMethodMap[M]['params']",
            "export type RpcResult<M extends RpcMethod> = RpcMethodMap[M]['result']",
            "export type RpcArgs<M extends RpcMethod> = {} extends RpcParams<M> ? [params?: RpcParams<M>] : [params: RpcParams<M>]",
            "export type RpcTransport = { request<M extends RpcMethod>(method: M, ...args: RpcArgs<M>): Promise<RpcResult<M>> }",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if checked-in contract is stale"
    )
    args = parser.parse_args()
    generated = generate()
    if args.check:
        existing = TARGET.read_text() if TARGET.exists() else ""
        if existing != generated:
            sys.stdout.writelines(
                difflib.unified_diff(
                    existing.splitlines(True),
                    generated.splitlines(True),
                    fromfile=str(TARGET),
                    tofile="generated",
                )
            )
            return 1
        print("RPC contract is up to date")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(generated)
        print(f"Generated {TARGET} ({len(RPC_METHODS)} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
